/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArticleItem: typeof import('./src/components/ArticleItem/index.vue')['default']
    BarList: typeof import('./src/components/Nav/BarList.vue')['default']
    Card: typeof import('./src/components/CardList/index.vue')['default']
    CardList: typeof import('./src/components/CardList/index.vue')['default']
    ChangeTheme: typeof import('./src/components/Nav/ChangeTheme.vue')['default']
    ContentList: typeof import('./src/components/ContentList/index.vue')['default']
    DateInfo: typeof import('./src/components/DateInfo/index.vue')['default']
    DetailMk: typeof import('./src/components/DetailMk/index.vue')['default']
    DetailTitleTips: typeof import('./src/components/DetailTitleTips/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    GoTop: typeof import('./src/components/GoTop/index.vue')['default']
    HoverCard: typeof import('./src/components/HoverCard/index.vue')['default']
    HoverImg: typeof import('./src/components/HoverImg.vue')['default']
    HoverScaleImg: typeof import('./src/components/HoverScaleImg/HoverScaleImg.vue')['default']
    Indev: typeof import('./src/components/Loading/indev.vue')['default']
    Loading: typeof import('./src/components/Loading/index.vue')['default']
    MobileSearchTop: typeof import('./src/components/MobileSearchTop/index.vue')['default']
    Nav: typeof import('./src/components/Nav/index.vue')['default']
    OrbitSpinner: typeof import('./src/components/Loading/OrbitSpinner.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader/index.vue')['default']
    Paginagn: typeof import('./src/components/paginagn.vue')['default']
    Pagination: typeof import('./src/components/Pageination/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Selected: typeof import('./src/components/Selected/index.vue')['default']
  }
}
