/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BarList: typeof import('./src/components/Nav/BarList.vue')['default']
    Card: typeof import('./src/components/CardList/index.vue')['default']
    CardList: typeof import('./src/components/CardList/index.vue')['default']
    ChangeTheme: typeof import('./src/components/Nav/ChangeTheme.vue')['default']
    ContentList: typeof import('./src/components/ContentList/index.vue')['default']
    DetailMk: typeof import('./src/components/DetailMk/index.vue')['default']
    DetailTitleTips: typeof import('./src/components/DetailTitleTips/index.vue')['default']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    GoTop: typeof import('./src/components/GoTop/index.vue')['default']
    HoverImg: typeof import('./src/components/HoverImg.vue')['default']
    HoverScaleImg: typeof import('./src/components/HoverScaleImg/HoverScaleImg.vue')['default']
    Nav: typeof import('./src/components/Nav/index.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader/index.vue')['default']
    Paginagn: typeof import('./src/components/paginagn.vue')['default']
    Pagination: typeof import('./src/components/Pageination/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
