/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArticleItem: typeof import('./src/components/ArticleItem/index.vue')['default']
    ArticleSearch: typeof import('./src/components/ArticleSearch/index.vue')['default']
    BarList: typeof import('./src/components/Nav/BarList.vue')['default']
    Btns: typeof import('./src/components/Btns/index.vue')['default']
    ChangeTheme: typeof import('./src/components/Nav/ChangeTheme.vue')['default']
    DateInfo: typeof import('./src/components/DateInfo/index.vue')['default']
    DetailMk: typeof import('./src/components/DetailMk/index.vue')['default']
    DetailTitleTips: typeof import('./src/components/DetailTitleTips/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    FootBA: typeof import('./src/components/FootBA/index.vue')['default']
    GoTop: typeof import('./src/components/GoTop/index.vue')['default']
    HomeBg: typeof import('./src/components/HomeBg/index.vue')['default']
    HoverScaleImg: typeof import('./src/components/HoverScaleImg/HoverScaleImg.vue')['default']
    LeaveWord: typeof import('./src/components/LeaveWord/index.vue')['default']
    Loading: typeof import('./src/components/Loading/index.vue')['default']
    MobileInfoTop: typeof import('./src/components/MobileInfoTop/index.vue')['default']
    Nav: typeof import('./src/components/Nav/index.vue')['default']
    OrbitSpinner: typeof import('./src/components/Loading/OrbitSpinner.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader/index.vue')['default']
    Pagination: typeof import('./src/components/Pageination/Pagination.vue')['default']
    ProgressImg: typeof import('./src/components/ProgressImg/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Selected: typeof import('./src/components/Selected/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
